title: MakSIL
baseURL: 'https://example.com/'
defaultContentLanguage: en
enableRobotsTXT: true
summaryLength: 30
pagination:
  pagerSize: 10
outputs:
  home: [HTML, RSS]
  section: [HTML, RSS]
taxonomies: {}
markup:
  goldmark:
    renderer:
      unsafe: false
